const message = {
    SUCCESS: 'success',
    FAILED: 'failed',
    SERVER_ERROR: 'Internal Server Error',
    CREATED: 'Created Successfully',
    UPDATED: 'Updated Successfully',
    DELETED: 'Deleted Successfully',
    FETCHED: 'Data Retrieved Successfully',
    USER_NOT_FOUND: 'User not found',
    ALREADY: 'User already exist',
    NOT_FOUND: 'Email not found',
    OTP_EXPIRED: "OTP has expired",
    INVALID_OTP: "Invalid OTP",
    OTP_VERIFIED: "OTP verified successfully",
    EMAIL_VERIFICATION_SUBJECT: "Verify Your Email Address",
    EMAIL_VERIFIED: "Email is already verified.",
    OTP_RESENT_SUCCESSFULLY: "A new verification code has been sent to your email.",
    EMAIL_ALREADY_REGISTERED: "Email already registered. Please verify your email or request a new OTP.",
    INVALID_PASSWORD: "Invalid password.",
    LOGIN_SUCCESS: "Login successful.",
    EMAIL_NOT_VERIFIED: "Please verify your email address before continuing.",
    REFRESH_TOKEN_REQUIRED: "Refresh token is required",
    INVALID_REFRESH_TOKEN: "Invalid refresh token",
    LOGOUT_SUCCESS: "LogOut successful",
    FORGOT_PASSWORD: "If an account exists with this email, a password reset OTP has been sent.",
    INVALID_OTP: "Invalid OTP",
    OTP_EXPIRED: "OTP has expired",
    OTP_COOLDOWN: "Please wait before requesting another OTP.",
    PASSWORD_RESET_NOT_FOUND: "Password reset request not found.",
    OTP_ATTEMPTS_EXCEEDED: "Too many incorrect OTP attempts. Please request a new OTP.",
    RESET_TOKEN_NOT_FOUND: "Invalid  password reset token.",
    RESET_TOKEN_EXPIRED: "Password reset token has expired.",
    OTP_VERIFIED: "OTP verified successfully. You can now reset your password.",
    RESET_PASSWORD_SUCCESS: "Password reset successfully.",
    AUTHENTICATION_REQUIRED: "Authentication required.",
    INVALID_OR_EXPIRED_TOKEN: "Invalid or expired token.",
    CURRENT_PASSWORD_INCORRECT: "Current password is incorrect.",
    PASSWORD_CHANGED_SUCCESSFULLY: "Password changed successfully.",
    TODO_CREATED:"Todo Created Successfully",
    TODO_NOT_FOUND:"Todo not found",
    TRASH_EMPTY:"Trash is empty",

}
export default message;