import express from 'express';
import authRouter from './auth/auth.routes.js';
import errorHandler from './middlewares/error.middleware.js';
import cookieParser from 'cookie-parser';
import userRouter from './users/user.routes.js';
import { todoRouter } from './todos/todo.routes.js';
const app=express();
app.use(express.json());
app.use(cookieParser());
app.use('/api/v1/auth',authRouter);
app.use('/api/v1/users',userRouter);
app.use('/api/v1',todoRouter);
app.use(errorHandler);
export default app;